### ISSUE TITLE
Unable to use without a google API key

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/google_fonts#6]
Got this: "The list of Google Fonts could not be fetched. Verify that your server can connect the Google Servers (https://www.googleapis.com). Error: Bad Request"

And found [this issue](https://www.drupal.org/project/fontyourface/issues/3183601) in the Drupal version of the module. Tried to create an developer API key at google and become really overwhelmed with how much was needed here, and even with the API key in hand, I suppose I would need to change the module code which is not really a viable options. Any advice here?

**Comment by PepeMty** [comment]
Hey there...!
I have the very same issue that ghost reported here.
Can somebody point me in the right direction...?

Thanks.

**Comment by herbdool** [comment]
As a short term solution people could download the fonts and use `@font-face` https://css-tricks.com/snippets/css/using-font-face/ to embed them in the css.

I don't think it would take too much work to fix this bug - would require getting people to set the key in settings.php and then the module calls it to append to the URL.

**Comment by Graham-72** [comment]
I have a fix for this ready to make a PR. It will include a new 'default' key and also provide an admin option to change to a different key.  PR #8

**Comment by Graham-72** [comment]
Fixed with PR #8
