### ISSUE TITLE
Maintainer?

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/google_fonts#7]
@Graham-72 are you the maintainer of this module? If so I recommend adding a Maintainer section in the README and adding your name there. If not, then I guess this is an open call to see who would like to maintain it.

**Comment by Graham-72** [comment]
@herbdool I have produced a revised README.md, including myself as a maintainer, as part of PR #8 .

**Comment by herbdool** [comment]
Looks good to me!

**Comment by Graham-72** [comment]
@herbdool I don't seem to have the right in GitHub to merge the PR or add a label that the bug can now be fixed.

**Comment by herbdool** [comment]
I don't have access either. Maybe @klonos can fix the permissions.

**Comment by Graham-72** [comment]
Fixed in PR #8
